### ISSUE TITLE
Possible XSS issue with searches using GET

### ISSUE THREAD

**Issue by jeffwhitfield** [splittingred/SimpleSearch#19]
Had a client email me with this:

Go here http://www.nsslabs.com/search-results.html?search=Hello+NSS+Labs%22+onmouseover%3D%22alert%28document.cookie%29%3B and move your mouse on the search box.

Should this be a concern?

**Comment by oori** [comment]
as long as the queries are not kept somewhere and presented to other logged in users (which i doubt if someone does...) - i don't see an issue with that.

comments/blackboards are more suspected to that kind of attacks.

**Comment by mikrobi** [comment]
this should defenitly be fixed. When you use the [[+searchValue]] placeholder from the SimpleSearchForm snippet like described in the docu one can hack your site. For example by using a search term like
">< iframe src="http://www.bad-site.com">< /iframe>

You should always clean user inputs before displaying them in the frontend!!

**Comment by oori** [comment]
I disagree about this being a critical issue, as it's no persistent data, but still - 
with XSS there's always the question of what's better - to filter on input -or- escape on output (or both...).  
parseSearchString function takes care for input santization (based on modx class's sanitizePatterns which should probably be updated...). 

this is a case where escaping the output gives the 'missing protection':

in "SearchForm" chunk change
value="[[+searchValue]]"
value="[[+searchValue:htmlent]]"

**Comment by mikrobi** [comment]
It might be critical if someone points you to an URL like http://www.good.com?search=">< iframe+src%3D"http%3A%2F%2Fwww.bad.com"><%2Fiframe>
Or executes some JS which reads cookie data.

Of course you have to use value="[[+searchValue:htmlent]]" but this should be mentioned in the docu and should even be done in the default template.

**Comment by oori** [comment]
I would be happy to understand how exactly can this be used against other people but yourself.
as long as the input is not persistent - meaning - it's not saved somewhere in the database and rendered later for other people to see (and get affected by the XSS), I can only see that you can "attack yourself",  the equivalent of opening firebug and doing alert(document.cookie).
feel free to correct me.  "web security" is far from being a single-answer field...

in any case - as you suggested, I have added that :htmlent filter to the default searchform (https://github.com/splittingred/SimpleSearch/pull/25)

**Comment by jeffwhitfield** [comment]
I think the only real threat is if another site is linking to a site with a SimpleSearch form. Granted, can't really hurt anything server-side unless there's a vulnerability...but they can cause a browser-side scare. For security purposes, it's probably a good idea to cleanse the input of any bogus code just to be on the safe side.  Definitely not critical but, after thinking about it, probably a necessary evil.

**Comment by splittingred** [comment]
This was fixed in a recent pull request merge. Thanks guys!
