### ISSUE TITLE
Problems with search in GET vs POST

### ISSUE THREAD

**Issue by splittingred** [splittingred/SimpleSearch#2]
See http://modxcms.com/forums/index.php/topic,50034.0.html

**Comment by splittingred** [comment]
I can't seem to replicate this at all; betting it's a local server issue.

**Comment by markbrown4** [comment]
The query string gets replaced by the get parameters so when using method="get" you need to add &lt;input type="hidden" name="id" value="[[+landing:default=`[[*id]]`]]" /&gt; in the search form.  You also must disable caching of the landing page for the search to return results when using get.
