### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by avoronkin** [splittingred/SimpleSearch#3]
Russian translation http://dl.dropbox.com/u/3483977/russian.translation.simplesearch.10beta1.zip

properties.inc.php - Good idea to do a translation for a Property Set, but for some reason it does not work for me (Revolution 2.0.0-rc-3 rev7048)

**Comment by splittingred** [comment]
Added in 1.0.0-beta2.

The properties.inc.php file wont translate until we reach Revo RC-3; it was a core bug in Revo that wasnt allowing property translations. That's been fixed in SVN, but I'm not going to release a fix for it in SimpleSearch until Revo's released (to prevent confusion).
