### ISSUE TITLE
Please escape double-quotes

### ISSUE THREAD

**Issue by goldsky** [splittingred/SimpleSearch#31]
double-quotes needs to be escaped ( '"' => '&quot;' ), or the SimpleSearchForm will start to harm by javascript infection.

**Comment by splittingred** [comment]
Not sure what you mean - can you be specific as to how quotes would cause XSS?

**Comment by goldsky** [comment]
try search:
    modx" onFocus="alert('hello')

without double quotes in front and behind it

**Comment by splittingred** [comment]
Fixed in https://github.com/splittingred/SimpleSearch/commit/215df2c5d85a8acda8ce48892904e48f2d2531eb
