### ISSUE TITLE
pagination problem with recent simple search 1.2.0. on revo 2.0.8

### ISSUE THREAD

**Issue by dez-01tiu2** [splittingred/SimpleSearch#32]
when using simple search, the search redirects to the landing page with results, but when clicking on a pagination link on the search landing page to more search results, no search results appear, just the text:

There were no search results. Please try using more general terms to get more results.

same across all my sites and clients sites which I have updated over the past day.

**Comment by ghost** [comment]
The offset seems to be calculated improperly in the latest version. For a quick fix:

Open core/components/simplesearch/model/simplesearch/simplesearch.class.php

Find the following:

```
$offset = ($_REQUEST[$offsetIndex]-1)*$perPage;
```

Replace with: 

```
$offset = $_REQUEST[$offsetIndex];
```

**Comment by dez-01tiu2** [comment]
appreciate the help, but there is a problem: the file already contains the code you suggested:

$offset = $_REQUEST[$offsetIndex];

**Comment by splittingred** [comment]
Fixed.
