### ISSUE TITLE
Use TV's as placeholders

### ISSUE THREAD

**Issue by glenwith1n** [splittingred/SimpleSearch#34]
I have 3 or 4 product websites I am developing at the moment in revo and have just realised I cant do a product search to display images, a product site without being able to search for the actual products isn't real user friendly. So if you could add this feature it would be much appreciated.

**Comment by marcushouse** [comment]
Also need this. Please include.

**Comment by splittingred** [comment]
This is already fixed as of 1.4.0; just use &includeTVs=`1` (and &processTVs=`1` if you need to process them).

**Comment by glenwith1n** [comment]
Thankyou for adding this, it would also be nice if you could add &includeTVList=  and also &processTVList= as per getresources as this would speed up the search dramatically.
