### ISSUE TITLE
German translation: wrong charset

### ISSUE THREAD

**Issue by feeela** [splittingred/SimpleSearch#37]
The charset was ISO-8859-1, but it should be UTF-8 as all other translations to prevent umlaut-breaking.
As I can't commit, the german (de) language-files can be found here:
https://static.thomas-heuer.eu/snippets/core-components-simplesearch-lexicon-de.tar.bz2

**Comment by anselmh** [comment]
You can find files for 1.2.0pl here:
http://www.modxcms.de/forum/comments.php?CommentID=28048&&Download=SimpleSearch-de-files-utf8.zip

discussion here: http://www.modxcms.de/forum/comments.php?DiscussionID=4196&page=1#Item_5
