### ISSUE TITLE
Multiple search terms concatenated to one term in search box and results message

### ISSUE THREAD

**Issue by Stretch0204** [splittingred/SimpleSearch#39]
A search for "red cars" produces correct results with page URL: results.html?search=red+cars&x=27&y=10&id=15. Search box shows "redcars" and results message is "X results found for redcars". Pagination links are set to: results.html?search=redcars&sisea_offset=3 which when clicked give a "no results found" message because search term has changed to "redcars".

See http://modxcms.com/forums/index.php/topic,62169.0.html and http://modxcms.com/forums/index.php/topic,63242.0.html

Problem appears to have been introduced some time after v1.1.0. I updated a Rev 2.0.4 installation I had from a few months ago from  v1.1.0 to 1.3.0 rc2. No problems with 1.1.0, but after update to 1.3.0 rc2 through package management, I now have the concatenation issue. Experiencing the same issue on Rev 2.0.5 and 2.0.7 sites.

Console log after 1.3.0 rc2 update:

<pre>
Console running...
Attempting to install package with signature: simplesearch-1.3.0-rc2
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Attempting to preserve files at /my-site-path/core/components/simplesearch into archive /my-site-path/core/packages/simplesearch-1.3.0-rc2/modCategory/757ed0edb4a32eebabdb41ab93d73d38.0.preserved.zip
Successfully installed package simplesearch-1.3.0-rc2
</pre>

Error log after update:

<pre>
[2011-04-11 19:14:44] (ERROR @ /my-site-path/core/xpdo/compression/xpdozip.class.php : 142) PHP warning: ZipArchive::extractTo() [<a href='ziparchive.extractto'>ziparchive.extractto</a>]: File exists
[2011-04-11 19:14:44] (ERROR @ /connectors/workspace/packages.php) Could not unpack package /my-site-path/core/packages/simplesearch-1.3.0-rc2.transport.zip to /my-site-path/core/packages/. SIG: simplesearch-1.3.0-rc2
</pre>

I have a site with a Manager account you can use if that helps.

**Comment by mkschell** [comment]
This issue has been resolved in the following commit
https://github.com/splittingred/SimpleSearch/commit/d51cec037eac9a60c1b4c6915b1757321d9039eb
.. and will be included in the next release
