### ISSUE TITLE
Problem with paging

### ISSUE THREAD

**Issue by phron** [splittingred/SimpleSearch#4]
I call SimpleSearch in my results page with this call :
CODE:
[[!SimpleSearch? &perPage=`5`]]

I have ten results for my search request, so the "results pages" is 2, and is well displayed in the [[+paging]] placeholder, the problem is the first page displays all 10 results not only the first five. I expected to have the first five results on the first results page, the five next on the 2nd page, etc...
If I click on the second page, these one has its 5 results as expected...

**Comment by splittingred** [comment]
Fixed in 1.0.0-beta2

**Comment by phron** [comment]
fix seems not work, I created a new issue (#5)
