### ISSUE TITLE
SimpleSearch not sintalling from Package Management

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [splittingred/SimpleSearch#41]
When trying to install SimpleSearch in MODx Revolution 2.0.7-pl (traditional) I get the following error:

Console running...
Attempting to install package with signature: simplesearch-1.3.0-rc2
xPDOZip: Error opening archive at /home/designfr/public_html/qhp/core/packages/simplesearch-1.3.0-rc2.transport.zip
Could not install package with signature: simplesearch-1.3.0-rc2
Could not unpack package /home/designfr/public_html/qhp/core/packages/simplesearch-1.3.0-rc2.transport.zip to /home/designfr/public_html/qhp/core/packages/. SIG: simplesearch-1.3.0-rc2
Package found...now preparing to install.
PHP warning: ZipArchive::close() [ziparchive.close]: Invalid or unitialized Zip object
PHP warning: ZipArchive::extractTo() [ziparchive.extractto]: Invalid or unitialized Zip object

**Comment by u007** [comment]
ive had the same problem,... 
license agreement return:
{"success":false,"message":"","total":0,"data":[],"object":[]}

**Comment by ChrstnMgcn** [comment]
Same issue here.
MODX Revolution 2.1.0-rc1 (traditional)
When installing I get a blank License Agreement, Readme and Changelog.
Upon clicking finish I get:

Console running...
PHP warning: ZipArchive::extractTo() [ziparchive.extractto]: Invalid or unitialized Zip object
Package found...now preparing to install.
xPDOZip: Error opening archive at /home/imommodx/public_html/core/packages/simplesearch-1.3.0-rc2.transport.zip
Could not install package with signature: simplesearch-1.3.0-rc2
PHP warning: ZipArchive::close() [ziparchive.close]: Invalid or unitialized Zip object
Attempting to install package with signature: simplesearch-1.3.0-rc2
Could not unpack package /home/imommodx/public_html/core/packages/simplesearch-1.3.0-rc2.transport.zip to /home/imommodx/public_html/core/packages/. SIG: simplesearch-1.3.0-rc2

**Comment by Jako** [comment]
Some ZipArchive problems can be solved by set the MODX setting 'archive_with' to YES.

But with this package there is some other problem: It can't be installed by package management (maybe because of a corrupt transport package) on my installation. During the installation process the changelog of formit is shown. 

The downloaded zip from modx.com/extras/package uploaded to core/packages installs perfectly. This zip is 0.2 KB larger than the one from the package management.

**Comment by splittingred** [comment]
Not reproducible; more than likely due to a corrupt download or flawed ZipArchive setup on your environment. Set the setting archive_with to 1, and ensure cURL is properly setup on your server.
