### ISSUE TITLE
Cyrillic characters won't show in [[+searchValue]] and [[+text]] variables

### ISSUE THREAD

**Issue by belbiy** [splittingred/SimpleSearch#42]
Please see http://modx.com/search-results/?search=%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD

**Comment by Paprikas** [comment]
Additional comments on this issue
https://github.com/splittingred/SimpleSearch/commit/d51cec037eac9a60c1b4c6915b1757321d9039eb#comments

**Comment by splittingred** [comment]
Fixed in recent commit.
