### ISSUE TITLE
Simple Search returns priviliedge results ignoring Minimum Authority

### ISSUE THREAD

**Issue by wshawn** [splittingred/SimpleSearch#43]
In MODX Revolution 2.1.0-rc4 (traditional), I am able to search for key words which exist in documents even though anonymous users should not be able to do so.

**Comment by wshawn** [comment]
To clarify, SimpleSearch is set up for site wide search, but certain documents have restricted access. Simple Search returns all docs it finds.

**Comment by splittingred** [comment]
I think this is fixed in the upcoming 1.5.0, as now it checks the "list" permission before adding the Resource to the results.
