### ISSUE TITLE
Pagination - search result #1 is on second page

### ISSUE THREAD

**Issue by yoga123** [splittingred/SimpleSearch#44]
Using Revolution 2.0.8 Traditional - SimpleSearch 1.3.0.

This occurs when perPage is set to the default of 10 results per page (or basically when pagination comes into play). When a search is more than 10 results it puts result number 1 as number 1 on page 2.  The second result is then result 1 on page 1.

Thanks for the great extras and CMF!

**Comment by splittingred** [comment]
Can't reproduce this.

**Comment by yoga123** [comment]
Hello Shaun,

Thanks for trying. It is an odd one.  I just solved this on that website by turning pagination off.

Thanks so much for all of your work!!

God Bless and Best wishes,
Kris 

-----Original Message-----

**Comment by splittingred** [comment]
No problem Kris. It might be fixed in the most recent release.
