### ISSUE TITLE
The "no results" message can't be customized through a tpl

### ISSUE THREAD

**Issue by Martijn1981** [splittingred/SimpleSearch#46]
See my forum post http://modxcms.com/forums/index.php/topic,64682.0.html. 

I've submitted the search form with any values and though the message "There were no search results. Please try using more general terms to get more results." appears on my screen, there seems to be no way to customize it! It's not surrounded by paragraphs or spans! Please develop a &tpl parameter for this one.

**Comment by shaunmorrison** [comment]
Hi 

NOTE: 

You can use [[+query]] in your template to display the search query - e.g.
No results for "[[+query]]". Please try something else.

Many thanks, 
Shaun
