### ISSUE TITLE
Simplesearch to search different context instead of 1 context only

### ISSUE THREAD

**Issue by seekdiver** [splittingred/SimpleSearch#47]
Hi, is there a way to improve the simplesearch function to search different context instead of just 1 context itself? Such as :
Web              |-homepage
                      |- aboutus
                       - contact
anotherweb |- homepage
                       |- aboutus
                        - contact

So when the simplsearch is place in Web - homepage, the function will also be able to search the anotherweb -homepage, aboutus, contact. 

Please advice. Thanks!

**Comment by splittingred** [comment]
Use the &contexts parameter.
