### ISSUE TITLE
cultureKey doesn't work with noResultsTpl in latest release

### ISSUE THREAD

**Issue by Martijn1981** [splittingred/SimpleSearch#48]
As stated in the title: I've set my cultureKey to NL now and all the other placeholders seem to be generating their Dutch counterparts, but the noResults placeholder keeps outputting an English message.

Also, could you please update docs with the &noResultsTpl parameter? I have no idea what its default content is.

**Comment by rtripault** [comment]
According to https://github.com/splittingred/SimpleSearch/blob/develop/core/components/simplesearch/elements/snippets/simplesearch.snippet.php#L38 this parameter expects a chunk, by default https://github.com/splittingred/SimpleSearch/blob/develop/core/components/simplesearch/elements/chunks/searchnoresults.chunk.tpl is used
Hope that will help :)

**Comment by Martijn1981** [comment]
Thanks, but I'm confused. This tpl contains no lexicon namespaces, so it'll always be an English message, right? Shouldn't this chunk contain namespaces as well by default?

**Comment by splittingred** [comment]
Fixed.
