### ISSUE TITLE
Problem after last update... No result returned, no landing,...

### ISSUE THREAD

**Issue by phron** [splittingred/SimpleSearch#5]
Hello

I just updated SimpleSearch to beta 2, and now NOTHING work !  
All the things that worked with previous release (i.e: returns the good number of results, and landing) don't work anymore.

To be sure I tried the simplest, with the 2 calls in my template without any parameter
CODE:
[[!SimpleSearchForm]]
[[!SimpleSearch]]

// I tried too
[[!SimpleSearchForm? ]]
[[!SimpleSearch? ]]

Always returns "no result found".

I tried with &landing parameter, redirection works but display "no result"...

Of course I cannot test if paging works as expected now... 
Cheers

**Comment by splittingred** [comment]
Fixed in 1.0.0-beta3; was due to a bug in the contexts param. An odd one, too. Thanks for catching this.
