### ISSUE TITLE
simple search pagination issues 1.4.0

### ISSUE THREAD

**Issue by dez-01tiu2** [splittingred/SimpleSearch#50]
when you type a single word, pagination works fine, if you type in two words to the searchform, the landing page shows the first set correctly but if you click on the second page, simple search compresses those two words together and says no results found try using a more general term, remember this was an issue quite some time ago, but was fixed before there was any answer with an update. 

changing method in searchform from get to post, doesn't help either.
also my javascript comes back in the search extracts
still on revo 2.0.8 since just deployed site last night need to make sure on local host if the new revo release doesn't effect the site on localhost

**Comment by splittingred** [comment]
Fixed.
