### ISSUE TITLE
pagination issue, links return 404

### ISSUE THREAD

**Issue by dez-01tiu2** [splittingred/SimpleSearch#57]
I remember this being an issue a long time ago, I believe an update fixed the issue, but it's back, if I type a single word into the search, no problem, but if I type two words with a space it seems to return fine until I click onto another link in the pagination then it returns a 404
EDIT: modx revo 2.1.3 and Simplesearch 1.4.0
also looks &perPage is being ignored, I've googled like hell (after RTFM visit) but can't find a way to limit the pagination, like in getresources (or is it getpage?)

**Comment by splittingred** [comment]
1. This works fine for me, can you provide your SimpleSearch call?
2. perPage works fine for me as well.
