### ISSUE TITLE
highlightResults not working after upgrade to 1.5.1

### ISSUE THREAD

**Issue by jacobkball** [splittingred/SimpleSearch#60]
After upgrading to 1.5.1, the highlighting on the search term in results does not appear to be working.

**Comment by sparkyhd** [comment]
Confirmed - I've just found the same issue

**Comment by smanu85** [comment]
I've noticed that if you comment/delete line 89:

$extract = array_pop($search->searchArray);

inside SimpleSearch snippet, term highlighting starts to function again.

**Comment by sparkyhd** [comment]
Actually i've noticed mine started working again by itself.  The only thing that changed was I upgraded Wayfinder.  It can't be that though because it's unrelated, or is it?

**Comment by smanu85** [comment]
Me too I've the latest version of Wayfinder (2.3.3) installed in 2 different sites and SimpleSearch show this issue if I leave line 89 as default... I think it's not related to Wayfinder at all.

PHP's array_pop() function used in line 89 pops and returns the last value of a given array (in this case the searchArray which contains every terms to find).

In fact this issue in SimpleSearch snippet occurs ONLY if you search a single term.
If I search 2 (or more) terms the first one is highlighted but the last one not.

**Comment by jacobkball** [comment]
I also have the latest version of Wayfinder (2.3.3) and the highlighting wasn't working, so I don't think it's that.

I tried commenting out line 89, and that has worked for me - highlighting is back on.

I'm not sure why that line would be causing the issue - perhaps someone can shed some light on it!

**Comment by oblongd** [comment]
I am experiencing the same problem, running SimpleSearch 1.5.1pl on the Dec. 15th nightly build of Revo 2.2.0-rc2.  The last (or only) search term is never highlighted.
