### ISSUE TITLE
[[+extract]] does not work correctly with utf8

### ISSUE THREAD

**Issue by avoronkin** [splittingred/SimpleSearch#8]
[[+extract]] does not work correctly with utf8

**Comment by splittingred** [comment]
Explain - i'm using UTF-8 and it works fine. Can you give more details?

**Comment by avoronkin** [comment]
Yes, you are using UTF-8, but English in the UTF-8 encoded with one byte. I use the Russian language, which is encoded with two bytes. PHP processes strings based on bytes, not characters, and damage multibyte strings - for example, by splitting characters 'in half'.
Try past 2byte characters in yor page, for example ©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©©,
and search for ©©©©
[[!SimpleSearch? &extractLength=`25`]]
I get: ©©©©©©©©©©©©�...
And core output filters also not expected for work with multibyte strings:(

http://www.phpwact.org/php/i18n/utf-8
http://api.drupal.org/api/drupal/includes--unicode.inc

**Comment by splittingred** [comment]
Okay, cool. Thanks for the reference.

I've gone ahead and fixed this in the Revo core, and to implement the fix in SimpleSearch, I'll need to make it use the fixes in the Revo core (which is a setting called 'use_multibyte' - it's auto-set on new installs, but you'll have to toggle it on upgrades).

So, IOW, i wont release a new version of SimpleSearch until post-RC3. Luckily, RC-3 is to be released this week. :P
