### ISSUE TITLE
Deleting multiple resources via bulk action error

### ISSUE THREAD

**Issue by squarou** [splittingred/SimpleSearch#87]
Hi,

I have an error while trying to delete more than 2 resources, in Collections extra view. After investigations, the problem is relied to SimpleSearch. Here are some elements : 
1. I uses collections-3.0.2-pl in a MODX revolution 2.3.1-pl (traditional)
2. I created 3 resources (with NewsPublisher : don't know if that can help)
   I selected the 3 resources, clicked the "delete selected" under "bulk actions". Nothing happened. I click refresh button (not F5, the refresh icon in the pagination block at the bottom) and 2 have disappeared, one left and was still selected (checkbox checked) !
3. Stauts of the request : 200 ok
   Forms data :
   action :"mgr/resource/deletemultiple"
   ids :"67,66,63"
   HTTP_MODAUTH :"modx54495afc1b2582.85768801_154747fc824f220.07040476"

Answer request :
`<br /> <b>Fatal error</b>: Cannot redeclare SimpleSearchGetChildren() (previously declared in /home/xxx/demo/modx/core/cache/includes/elements/modplugin/8.include.cache.php:50) in <b>/home/xxx/demo/modx/core/cache/includes/elements/modplugin/8.include.cache.php</b> on line <b>63</b><br />`

Looks like wrapping SimpleSearchGetChildren function definition with `if(!function_exists(SimpleSearchGetChildren)) {}` should solve the problem, **but how** ?

Any help appreciated.

More info : https://github.com/modxcms/Collections/issues/107#issuecomment-64411649

**Comment by exside** [comment]
done here: https://github.com/modxcms/SimpleSearch/pull/13

**Comment by squarou** [comment]
Ok thanks. But, after clearing my browser's cache and modx cache many times, I tried 3 more times to delete multiple resources and got the same error message. I'll try later from another computer...

**Comment by exside** [comment]
where did you apply the change? in the filesystem on the ftp or via the Elements Tab > Plugins > Edit Plugin?

**Comment by squarou** [comment]
I did in the filesystem...
Now I've done editing the plugin in the element tab and it works like a charm  :)

Thanks a lot !!!
