### ISSUE TITLE
Snippet properties do not use translation from properties.inc.php

### ISSUE THREAD

**Issue by avoronkin** [splittingred/SimpleSearch#9]
Snippet properties do not use translation from properties.inc.php
SimpleSearch 1.0.0 beta3
MODx Revolution 2.0.0-pl rev7212

**Comment by splittingred** [comment]
Upgrade SimpleSearch to rc2

**Comment by avoronkin** [comment]
From where? I can only see SimpleSearch 1.0.0-beta3 in the package manager.

**Comment by splittingred** [comment]
hrm, well, wait a day, and I'll release rc3. Must have not released rc2 :P

**Comment by avoronkin** [comment]
It works!:) Thanks!
