### ISSUE TITLE
display template variables in results

### ISSUE THREAD

**Issue by sergeaubin** [splittingred/SimpleSearch#93]
is there a way to display template variables in results?

**Comment by fabvis** [comment]
[[!SimpleSearch? &includeTVs=`1` &processTVs=`1`]]

and in your results template : [[+yourTV]]

**Comment by sergeaubin** [comment]
i put it in my searchresults.chunk.tpl  but it does not show up

**Comment by fabvis** [comment]
Can i see your simplesearch call and your tpl code ?

**Comment by sergeaubin** [comment]
Call:   [[!SimpleSearchForm?&landing=7&includeTVs=1&processTVs=1]]

TPL:<div class="sisea-result">
    <a href="[[+link:is=``:then=`[[~[[+id]]]]`:else=`[[+link]]`]]" title="[[+longtitle]]"><div><img src="[[+sector-image]]"/></div><div>[[+pagetitle]]<div class="extract"><p>[[+extract]]</p></div></div></a>
    
</div>

**Comment by sergeaubin** [comment]
Call: [[!SimpleSearchForm?&landing=7&includeTVs=1&processTVs=1]]

**Comment by sergeaubin** [comment]
TPL: <div class="sisea-result">
    <a href="[[+link:is=``:then=`[[~[[+id]]]]`:else=`[[+link]]`]]" title="[[+longtitle]]"><div><img src="[[+sector-image]]"/></div><div>[[*sector-image]][[+sector-image]] [[+pagetitle]]<div class="extract"><p>[[+extract]]</p></div></div></a>
    
</div>

**Comment by sergeaubin** [comment]
cant paste

**Comment by sergeaubin** [comment]
i cant attach or past the tpl code  but i use [[+sector-image]]  which is the name of my tv

**Comment by fabvis** [comment]
[[!SimpleSearchForm? &landing=7]] for the form

[[!SimpleSearch? &includeTVs=1 &processTVs=1]] for the landing page (7)

**Comment by sergeaubin** [comment]
oh god!!!   i feel stupid! thanks for pointing that
